import React, { useState } from "react";
import { requestPrediction } from "./api";
import modelSummary from "./assets/model_summary.png";
import metricSummary from "./assets/evaluation.png";

export default function App() {
  // store inputs as strings
  const [features, setFeatures] = useState(["", "", "", ""]);
  const [result, setResult] = useState(null);
  const [loading, setLoading] = useState(false);
  const inputLabels = ["Product ID", "Store", "Date", "Quantity"];
  const productOptions = [
    "P0007",
    "P0001",
    "P0004",
    "P0005",
    "P0009",
    "P0006",
    "P0014",
    "P0002",
    "P0011",
    "P0013",
    "P0008",
    "P0003",
    "P0010",
    "P0012",
  ];
  const storeOptions = [
    { id: "S0001", name: "Kemang" },
    { id: "S0003", name: "Batu" },
    { id: "S0007", name: "Seturan" },
    { id: "S0011", name: "Pandanaran" },
    { id: "S0014", name: "Madiun" },
    { id: "S0016", name: "Kemang 2" },
    { id: "S0020", name: "Gresik" },
    { id: "S0030", name: "Malioboro" },
    { id: "S0031", name: "Darmo" },
    { id: "S0034", name: "Jember" },
    { id: "S0037", name: "Malioboro 2" },
    { id: "S0040", name: "Cihampelas" },
  ];

  function updateFeature(idx, value) {
    const next = [...features];
    next[idx] = value;
    setFeatures(next);
  }

  async function handlePredict() {
    setResult(null);
    // validate non-empty values
    const emptyIndex = features.findIndex((f) => String(f).trim() === "");
    if (emptyIndex !== -1) {
      setResult({ error: "Please fill all fields before predicting." });
      return;
    }
    setLoading(true);
    try {
      const postFeatures = await requestPrediction("/predict", features);
      setResult(postFeatures);
    } catch (e) {
      setResult({ error: e.message || String(e) });
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="container">
      <h2>Machine Learning Predictor for Pizza-Hut Revenue per Store</h2>
      <p>
        Please select product and store. Input date and quantity then click{" "}
        <strong>Predict</strong> button.
      </p>

      <div className="inputs">
        {features.map((v, i) => (
          <div key={i} className="field">
            <label>{inputLabels[i] || `Fitur ${i + 1}`}</label>
            {i === 0 ? (
              <select
                value={v}
                onChange={(e) => updateFeature(i, e.target.value)}
              >
                <option value="">Select Product</option>
                {productOptions.map((opt) => (
                  <option key={opt} value={opt}>
                    {opt}
                  </option>
                ))}
              </select>
            ) : i === 1 ? (
              <select
                value={v}
                onChange={(e) => updateFeature(i, e.target.value)}
              >
                <option value="">Select Store</option>
                {storeOptions.map((opt) => (
                  <option key={opt.id} value={opt.id}>
                    {opt.name}
                  </option>
                ))}
              </select>
            ) : i === 2 ? (
              <input
                type="date"
                value={v}
                onChange={(e) => updateFeature(i, e.target.value)}
              />
            ) : (
              <input
                type="number"
                value={v}
                placeholder="e.g. 10"
                onChange={(e) => updateFeature(i, e.target.value)}
              />
            )}
          </div>
        ))}
      </div>

      <button
        onClick={handlePredict}
        disabled={loading || features.some((f) => String(f).trim() === "")}
      >
        {loading ? "Process..." : "Predict"}
      </button>

      {result && (
        <div className="result">
          {result.error ? (
            <div className="error">Error: {result.error}</div>
          ) : (
            <>
              <div>
                <strong>Revenue :</strong>{" "}
                {(() => {
                  const val = Array.isArray(result)
                    ? result[0]
                    : result.probability;
                  const n = Number(val);
                  return Number.isFinite(n) ? n.toFixed(2) : val;
                })()}
              </div>
            </>
          )}
        </div>
      )}

      <p>
        This application uses a model implemented in Microsoft Foundry | Azure
        Machine Learning. Dataset is generated by ChatGPT and contains 100 rows
        and 5 features.
      </p>
      <div className="divImages">
        <img src={modelSummary} alt="Model summary" className="image1" />
        <img src={metricSummary} alt="Model evaluation" className="image2" />
      </div>

      <h2>Power BI Dashboard</h2>
      <div className="powerBI">
        <iframe
          title="Sales_to_store_semantic_dashboard"
          className="frame-powerbi"
          src="https://app.fabric.microsoft.com/reportEmbed?reportId=6d3affb7-3d3a-4635-8e16-f74687e3e2c4&autoAuth=true&ctid=59a5e237-dd70-4b9a-a00c-6738ed10d408"
          frameborder="0"
          allowFullScreen="true"
        ></iframe>
      </div>
    </div>
  );
}
